- name: Copy fluent bit yaml files
  copy:
    src: '{{ playbook_dir }}/build'
    dest: '{{ dest_dir }}'

- name: Deploy fluent bit
  shell: kubectl apply -f '{{ dest_dir }}/build'
  register: kubectl_result

- name: Show kubectl apply fluent bit
  debug:
    msg: "{{ kubectl_result.stdout_lines }}"
